### ISSUE TITLE
ACPI Errors persist Even after installing this firmware 

### ISSUE THREAD

**Issue by Elhossainy-Ahmed** [BeardOverflow/msi-ec#159] opened 2024-09-05 08:35 UTC
### Laptop model

MSI MOdern 14 b5m

### EC firmware version

14DLEMS1.105

### Description

I have installed msi_ec firmware to get rid of this acpi errors and AMD secure display failure but these errors seems to be persistent and my battery life is very bad it's barely last for one hour .
 `[    0.252268] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SBRG.EC0], AE_NOT_FOUND (20230628/dswload2-162)
[    0.252286] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)
[    0.804484] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GP17.MP2], AE_NOT_FOUND (20230628/psargs-330)
[    0.804512] ACPI Error: Aborting method \_SB.GPIO._EVT due to previous error (AE_NOT_FOUND) (20230628/psparse-529)`
`[    4.730589] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: query securedisplay TA failed. ret 0x0`
I am very glad to any one how can help me .

**Comment by glpnk** [comment] 2024-09-05 08:46
Module not fix any ACPI errors.

Try to switch from `modern standby` suspend mode to `s3` in extended bios settings

Do you have delayed charger detection?

To reduce power draw try to reduce max CPU clock

**Comment by Elhossainy-Ahmed** [comment] 2024-09-05 08:50
> Module not fix any ACPI errors.
> 
> Try to switch from `modern standby` suspend mode to `s3` in extended bios settings to fix `mp2` error
> 
> Do you have delayed charger detection?
> 
> To reduce power draw try to reduce max CPU clock

Yes i have delayed charger detection it takes about 10 sec to be detected 
how to  change suspend mode to` S3`   in bios

**Comment by glpnk** [comment] 2024-09-05 08:56
Okay, i have too on `modern c5m` device

Open BIOS, press `ctrl+alt+shift+f2`, try different combos of left and right buttons and in `amd pbs` you'll find some setting which have this 2 params

**Comment by glpnk** [comment] 2024-09-05 11:17
I don't know what this feature does, maybe try to update your bios

**Comment by Elhossainy-Ahmed** [comment] 2024-09-05 11:19
Unfortunately i have the latest biis update from msi

**Comment by glpnk** [comment] 2024-09-05 11:49
Okay, which distro you use?

**Comment by Elhossainy-Ahmed** [comment] 2024-09-05 11:53
Now i use void linux, but this errors occured with arch, debian, Ubuntu, opensuse tumbleweed and fedora

**Comment by glpnk** [comment] 2024-10-08 15:08
@safelyrestor33d Yo, sorry I forget to answer
 
+ This is about delayed charger detection
https://github.com/BeardOverflow/msi-ec/discussions/130#discussioncomment-9694621

+ Brightness issue https://github.com/BeardOverflow/msi-ec/discussions/130#discussioncomment-10881545

About sleep - I don't close the lid often, and if I close it I manually put it into sleep or use it powered on. But this probably have same source as charger detection

**Comment by glpnk** [comment] 2024-10-08 15:10
About ACPI Errors - this module is not intended to fix them. Some of them caused by outdated or incorrectly configured ACPI features in DSDT. Plus BIOS modifies DSDT when settings are changed, so it's pure BIOS errors

**Comment by MHLeventoglu** [comment] 2024-11-26 11:15
Hello I'm using MSI Delta 15 with ryzen7 5800h and  not updated the bios into latest version (which is released in 2023) and I'm currently using the one released in 2022. I'm getting those acpi errors while booting into ubuntu 20.04.6 and freezes my laptop after a while in os. But I don't have problem like tat when I disable acpi by booting with parameter acpi=off. Will the latest driver fix my issue ? Or could anyone manged to fix those ACPI errors ?

**Comment by glpnk** [comment] 2024-11-26 11:23
@MHLeventoglu Which exact ACPI errors you have? Module not fixes them at all! Ask MSI to fix them (impossible, I think). If you have delayed charger detection, I can say how to fix it. Other errors are different or free to ignore

**Comment by MHLeventoglu** [comment] 2024-11-26 14:48
![S41126-17464902.jpg](https://github.com/user-attachments/assets/582db13e-c97b-457e-95df-36110031b715)

This is the error message.

**Comment by glpnk** [comment] 2024-11-26 14:58
If I remember correctly, it's for dGPU power settings, but I don't recommend you to change secret bios settings related to this issue

**Comment by MHLeventoglu** [comment] 2024-11-26 15:07
What do you recommend for that? To contact with customer service (Which I don't trust they will fix)?

**Comment by glpnk** [comment] 2024-11-26 15:11
No, service will say that your device intended for Windows, I'll tag @mutchiko who tinkered with similar bug

**Comment by mutchiko** [comment] 2024-12-08 18:29
sorry for being late, i was mentioned here but didn't receive the notification,

@Elhossainy-Ahmed replying to your list of ACPI issues:

> ```[    0.252268] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SBRG.EC0], AE_NOT_FOUND (20230628/dswload2-162)```

i can't find anything about it, if you are sure that you have problems related to it you should start looking the acpi table file that has that bit of code.

>```[    0.252286] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)```

related to the previous error

>```[    0.804484] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GP17.MP2], AE_NOT_FOUND (20230628/psargs-330)```

related to iGPU that comes with ryzen CPUs, mainly the vega 8 iGPU, i have failed to understand what it is or what it does. i did some dirty digging and found that its related to sleep/suspend mode in BIOS, assuming from the way it was done, this must be an issue on all msi laptops with similar hardware; good news is, it seems to not affect anything and this code in the SSDT table (ACPI SSDT/DSDT tables) is result of lazy copy/paste from older amd iGPUs code, and it can be ignored.

>```[    0.804512] ACPI Error: Aborting method \_SB.GPIO._EVT due to previous error (AE_NOT_FOUND) (20230628/psparse-529)```

result of the previous mp2 error ```[\_SB.PCI0.GP17.MP2]``` they come together, and also go together

>```[    4.730589] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: query securedisplay TA failed. ret 0x0```

https://www.reddit.com/r/archlinux/comments/154qq7v/amdgpu_secure_display_error_on_boot/

"You don't need to worry about the secure display errors. That's some security feature for "mission-critical" displays that few if any consumer devices support. I've got three systems with AMD GPUs and they all show this error."

**Comment by Elhossainy-Ahmed** [comment] 2024-12-08 18:55
> sorry for being late, i was mentioned here but didn't receive the notification,
> 
> @Elhossainy-Ahmed replying to your list of ACPI issues:
> 
> > `[    0.252268] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.SBRG.EC0], AE_NOT_FOUND (20230628/dswload2-162)`
> 
> i can't find anything about it, if you are sure that you have problems related to it you should start looking the acpi table file that has that bit of code.
> 
> > `[    0.252286] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20230628/psobject-220)`
> 
> related to the previous error
> 
> > `[    0.804484] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GP17.MP2], AE_NOT_FOUND (20230628/psargs-330)`
> 
> related to iGPU that comes with ryzen CPUs, mainly the vega 8 iGPU, i have failed to understand what it is or what it does. i did some dirty digging and found that its related to sleep/suspend mode in BIOS, assuming from the way it was done, this must be an issue on all msi laptops with similar hardware; good news is, it seems to not affect anything and this code in the SSDT table (ACPI SSDT/DSDT tables) is result of lazy copy/paste from older amd iGPUs code, and it can be ignored.
> 
> > `[    0.804512] ACPI Error: Aborting method \_SB.GPIO._EVT due to previous error (AE_NOT_FOUND) (20230628/psparse-529)`
> 
> result of the previous mp2 error `[\_SB.PCI0.GP17.MP2]` they come together, and also go together
> 
> > `[    4.730589] amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: query securedisplay TA failed. ret 0x0`
> 
> https://www.reddit.com/r/archlinux/comments/154qq7v/amdgpu_secure_display_error_on_boot/
> 
> "You don't need to worry about the secure display errors. That's some security feature for "mission-critical" displays that few if any consumer devices support. I've got three systems with AMD GPUs and they all show this error."

Thank you for your effort

**Comment by mutchiko** [comment] 2024-12-08 19:53
@MHLeventoglu when system freezes, do you need to restart to make it work again?

in the image you posted, i only see the most common ACPI problems, and im positive they don't relate to the freezing problem.

check for other ACPI problems AFTER booting with acpi functionality enabled using this command ```sudo dmesg | grep ACPI``` or ```sudo dmesg | grep error``` and share the output with us so we can see possible problems/solutoins.

**Comment by mutchiko** [comment] 2024-12-08 20:09
**let's clear a few points:**

as @glpnk said multiple times, msi-ec   **can't** and **won't** be able to fix ACPI erros. these are two different things.

this types of errors is handled by kernel maintainers, but don't go and report these problems; because the only fix is with the firmware developers. in other words MSI themselves.

you can follow the [arch wiki](https://wiki.archlinux.org/title/DSDT) to override and fix the tables yourself, and if you actually succeed, please share your solution in this [discussion](https://github.com/BeardOverflow/msi-ec/discussions/130#).

don't hope for msi support to help you with this, they don't know anything better than telling you to send your device for a repair that you don't need. and if you mention linux, they will flag your msi account and might refuse warranty claims if anything happens (linux is a good reason to void warranty even if the problem is not related to it).

**Comment by MHLeventoglu** [comment] 2024-12-09 10:35
```
 
[    0.000000] BIOS-e820: [mem 0x000000000a200000-0x000000000a20efff] ACPI NVS
[    0.000000] BIOS-e820: [mem 0x00000000eb341000-0x00000000eb3a0fff] ACPI data
[    0.000000] BIOS-e820: [mem 0x00000000eb3a1000-0x00000000eb558fff] ACPI NVS
[    0.000000] reserve setup_data: [mem 0x000000000a200000-0x000000000a20efff] ACPI NVS
[    0.000000] reserve setup_data: [mem 0x00000000eb341000-0x00000000eb3a0fff] ACPI data
[    0.000000] reserve setup_data: [mem 0x00000000eb3a1000-0x00000000eb558fff] ACPI NVS
[    0.000000] efi: ACPI=0xeb542000 ACPI 2.0=0xeb542014 TPMFinalLog=0xeb50e000 SMBIOS=0xed01f000 SMBIOS 3.0=0xed01e000 MEMATTR=0xe5a30018 ESRT=0xe87eed98 MOKvar=0xed071000 RNG=0xeb353018 TPMEventLog=0xe5a03018 
[    0.004360] ACPI: Early table checksum verification disabled
[    0.004363] ACPI: RSDP 0x00000000EB542014 000024 (v02 MSI_NB)
[    0.004366] ACPI: XSDT 0x00000000EB541728 000114 (v01 MSI_NB MEGABOOK 01072009 AMI  01000013)
[    0.004370] ACPI: FACP 0x00000000EB392000 000114 (v06 MSI_NB MEGABOOK 01072009 AMI  00010013)
[    0.004374] ACPI: DSDT 0x00000000EB385000 00CA7C (v02 MSI_NB MEGABOOK 01072009 INTL 20190509)
[    0.004376] ACPI: FACS 0x00000000EB50C000 000040
[    0.004378] ACPI: SLIC 0x00000000EB3A0000 000176 (v01 MSI_NB MEGABOOK 01072009 AMI  01000013)
[    0.004379] ACPI: SSDT 0x00000000EB398000 0072B0 (v02 AMD    AmdTable 00000002 MSFT 04000000)
[    0.004381] ACPI: IVRS 0x00000000EB397000 0001A4 (v02 AMD    AmdTable 00000001 AMD  00000000)
[    0.004383] ACPI: SSDT 0x00000000EB393000 003A21 (v01 AMD    AMD AOD  00000001 INTL 20190509)
[    0.004385] ACPI: FIDT 0x00000000EB384000 00009C (v01 MSI_NB MEGABOOK 01072009 AMI  00010013)
[    0.004387] ACPI: ECDT 0x00000000EB383000 0000C1 (v01 MSI_NB MEGABOOK 01072009 AMI. 00010013)
[    0.004389] ACPI: MCFG 0x00000000EB382000 00003C (v01 MSI_NB MEGABOOK 01072009 MSFT 00010013)
[    0.004391] ACPI: HPET 0x00000000EB381000 000038 (v01 MSI_NB MEGABOOK 01072009 AMI  00000005)
[    0.004393] ACPI: VFCT 0x00000000EB373000 00D884 (v01 MSI_NB MEGABOOK 00000001 AMD  31504F47)
[    0.004395] ACPI: BGRT 0x00000000EB372000 000038 (v01 MSI_NB MEGABOOK 01072009 AMI  00010013)
[    0.004396] ACPI: TPM2 0x00000000EB371000 00004C (v04 MSI_NB MEGABOOK 00000001 AMI  00000000)
[    0.004398] ACPI: SSDT 0x00000000EB36B000 005354 (v02 AMD    AmdTable 00000001 AMD  00000001)
[    0.004400] ACPI: CRAT 0x00000000EB36A000 000EE8 (v01 AMD    AmdTable 00000001 AMD  00000001)
[    0.004402] ACPI: CDIT 0x00000000EB369000 000029 (v01 AMD    AmdTable 00000001 AMD  00000001)
[    0.004404] ACPI: SSDT 0x00000000EB368000 000149 (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004406] ACPI: SSDT 0x00000000EB366000 00148E (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004407] ACPI: SSDT 0x00000000EB364000 00151E (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004409] ACPI: SSDT 0x00000000EB363000 000696 (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004411] ACPI: SSDT 0x00000000EB361000 001A56 (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004413] ACPI: SSDT 0x00000000EB360000 0005DE (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004415] ACPI: SSDT 0x00000000EB35C000 0036E9 (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004417] ACPI: WSMT 0x00000000EB35B000 000028 (v01 MSI_NB MEGABOOK 01072009 AMI  00010013)
[    0.004419] ACPI: APIC 0x00000000EB35A000 0000DE (v03 MSI_NB MEGABOOK 01072009 AMI  00010013)
[    0.004420] ACPI: SSDT 0x00000000EB359000 00008D (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004422] ACPI: SSDT 0x00000000EB358000 0008A8 (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004424] ACPI: SSDT 0x00000000EB357000 0001B7 (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004426] ACPI: SSDT 0x00000000EB356000 00079E (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004428] ACPI: SSDT 0x00000000EB355000 00097D (v01 AMD    AmdTable 00000001 INTL 20190509)
[    0.004429] ACPI: FPDT 0x00000000EB354000 000044 (v01 MSI_NB MEGABOOK 01072009 AMI  01000013)
[    0.004431] ACPI: Reserving FACP table memory at [mem 0xeb392000-0xeb392113]
[    0.004432] ACPI: Reserving DSDT table memory at [mem 0xeb385000-0xeb391a7b]
[    0.004433] ACPI: Reserving FACS table memory at [mem 0xeb50c000-0xeb50c03f]
[    0.004433] ACPI: Reserving SLIC table memory at [mem 0xeb3a0000-0xeb3a0175]
[    0.004434] ACPI: Reserving SSDT table memory at [mem 0xeb398000-0xeb39f2af]
[    0.004435] ACPI: Reserving IVRS table memory at [mem 0xeb397000-0xeb3971a3]
[    0.004435] ACPI: Reserving SSDT table memory at [mem 0xeb393000-0xeb396a20]
[    0.004436] ACPI: Reserving FIDT table memory at [mem 0xeb384000-0xeb38409b]
[    0.004436] ACPI: Reserving ECDT table memory at [mem 0xeb383000-0xeb3830c0]
[    0.004437] ACPI: Reserving MCFG table memory at [mem 0xeb382000-0xeb38203b]
[    0.004437] ACPI: Reserving HPET table memory at [mem 0xeb381000-0xeb381037]
[    0.004438] ACPI: Reserving VFCT table memory at [mem 0xeb373000-0xeb380883]
[    0.004439] ACPI: Reserving BGRT table memory at [mem 0xeb372000-0xeb372037]
[    0.004439] ACPI: Reserving TPM2 table memory at [mem 0xeb371000-0xeb37104b]
[    0.004440] ACPI: Reserving SSDT table memory at [mem 0xeb36b000-0xeb370353]
[    0.004440] ACPI: Reserving CRAT table memory at [mem 0xeb36a000-0xeb36aee7]
[    0.004441] ACPI: Reserving CDIT table memory at [mem 0xeb369000-0xeb369028]
[    0.004442] ACPI: Reserving SSDT table memory at [mem 0xeb368000-0xeb368148]
[    0.004442] ACPI: Reserving SSDT table memory at [mem 0xeb366000-0xeb36748d]
[    0.004443] ACPI: Reserving SSDT table memory at [mem 0xeb364000-0xeb36551d]
[    0.004443] ACPI: Reserving SSDT table memory at [mem 0xeb363000-0xeb363695]
[    0.004444] ACPI: Reserving SSDT table memory at [mem 0xeb361000-0xeb362a55]
[    0.004444] ACPI: Reserving SSDT table memory at [mem 0xeb360000-0xeb3605dd]
[    0.004445] ACPI: Reserving SSDT table memory at [mem 0xeb35c000-0xeb35f6e8]
[    0.004446] ACPI: Reserving WSMT table memory at [mem 0xeb35b000-0xeb35b027]
[    0.004446] ACPI: Reserving APIC table memory at [mem 0xeb35a000-0xeb35a0dd]
[    0.004447] ACPI: Reserving SSDT table memory at [mem 0xeb359000-0xeb35908c]
[    0.004447] ACPI: Reserving SSDT table memory at [mem 0xeb358000-0xeb3588a7]
[    0.004448] ACPI: Reserving SSDT table memory at [mem 0xeb357000-0xeb3571b6]
[    0.004449] ACPI: Reserving SSDT table memory at [mem 0xeb356000-0xeb35679d]
[    0.004449] ACPI: Reserving SSDT table memory at [mem 0xeb355000-0xeb35597c]
[    0.004450] ACPI: Reserving FPDT table memory at [mem 0xeb354000-0xeb354043]
[    0.022936] ACPI: PM-Timer IO Port: 0x808
[    0.022943] ACPI: LAPIC_NMI (acpi_id[0xff] high edge lint[0x1])
[    0.022962] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.022963] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 low level)
[    0.022965] ACPI: Using ACPI (MADT) for SMP configuration information
[    0.022966] ACPI: HPET id: 0x10228201 base: 0xfed00000
[    0.070492] ACPI: Core revision 20210730
[    0.260189] ACPI: PM: Registering ACPI NVS region [mem 0x0a200000-0x0a20efff] (61440 bytes)
[    0.260189] ACPI: PM: Registering ACPI NVS region [mem 0xeb3a1000-0xeb558fff] (1802240 bytes)
[    0.264048] ACPI: bus type PCI registered
[    0.264048] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    0.267060] ACPI: Added _OSI(Module Device)
[    0.267060] ACPI: Added _OSI(Processor Device)
[    0.267060] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.267060] ACPI: Added _OSI(Processor Aggregator Device)
[    0.267060] ACPI: Added _OSI(Linux-Dell-Video)
[    0.267060] ACPI: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
[    0.267060] ACPI: Added _OSI(Linux-HPI-Hybrid-Graphics)
[    0.267060] ACPI: Added _OSI(Linux)
[    0.297436] ACPI: 16 ACPI AML tables successfully acquired and loaded
[    0.299312] ACPI: EC: EC started
[    0.299313] ACPI: EC: interrupt blocked
[    0.301829] ACPI: EC: EC_CMD/EC_SC=0x66, EC_DATA=0x62
[    0.301830] ACPI: EC: Boot ECDT EC used to handle transactions
[    0.302968] ACPI: [Firmware Bug]: BIOS _OSI(Linux) query honored via cmdline
[    0.306598] ACPI: Interpreter enabled
[    0.306615] ACPI: PM: (supports S0 S4 S5)
[    0.306616] ACPI: Using IOAPIC for interrupt routing
[    0.306933] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.307649] ACPI: Enabled 1 GPEs in block 00 to 1F
[    0.308421] ACPI: PM: Power Resource [M237]
[    0.308678] ACPI: PM: Power Resource [M237]
[    0.308803] ACPI: PM: Power Resource [M237]
[    0.309695] ACPI: PM: Power Resource [WRST]
[    0.309728] ACPI: PM: Power Resource [DRST]
[    0.310353] ACPI: PM: Power Resource [P0U0]
[    0.310381] ACPI: PM: Power Resource [P3U0]
[    0.310821] ACPI: PM: Power Resource [P0U1]
[    0.310848] ACPI: PM: Power Resource [P3U1]
[    0.312776] ACPI: PM: Power Resource [P0NV]
[    0.313072] ACPI: PM: Power Resource [P0NV]
[    0.321421] ACPI: PM: Power Resource [PRWB]
[    0.323995] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.337291] ACPI: PCI: Interrupt link LNKA configured for IRQ 0
[    0.337364] ACPI: PCI: Interrupt link LNKB configured for IRQ 0
[    0.337429] ACPI: PCI: Interrupt link LNKC configured for IRQ 0
[    0.337507] ACPI: PCI: Interrupt link LNKD configured for IRQ 0
[    0.337577] ACPI: PCI: Interrupt link LNKE configured for IRQ 0
[    0.337636] ACPI: PCI: Interrupt link LNKF configured for IRQ 0
[    0.337695] ACPI: PCI: Interrupt link LNKG configured for IRQ 0
[    0.337754] ACPI: PCI: Interrupt link LNKH configured for IRQ 0
[    0.342385] ACPI: EC: interrupt unblocked
[    0.342386] ACPI: EC: event unblocked
[    0.342391] ACPI: EC: EC_CMD/EC_SC=0x66, EC_DATA=0x62
[    0.342392] ACPI: EC: GPE=0x3
[    0.342394] ACPI: \_SB_.PCI0.SBRG.EC__: Boot ECDT EC initialization complete
[    0.342396] ACPI: \_SB_.PCI0.SBRG.EC__: EC: Used to handle transactions and events
[    0.342704] ACPI: bus type USB registered
[    0.348658] PCI: Using ACPI for IRQ routing
[    0.367798] pnp: PnP ACPI init
[    0.369945] pnp: PnP ACPI: found 5 devices
[    0.455725] ACPI: AC: AC Adapter [ADP1] (on-line)
[    0.455831] ACPI: button: Lid Switch [LID0]
[    0.455882] ACPI: button: Power Button [PWRB]
[    0.455937] ACPI: button: Sleep Button [SLPB]
[    0.455986] ACPI: \_SB_.PLTF.P000: Found 3 idle states
[    0.456097] ACPI: \_SB_.PLTF.P001: Found 3 idle states
[    0.456197] ACPI: \_SB_.PLTF.P002: Found 3 idle states
[    0.456332] ACPI: \_SB_.PLTF.P003: Found 3 idle states
[    0.456473] ACPI: \_SB_.PLTF.P004: Found 3 idle states
[    0.456610] ACPI: \_SB_.PLTF.P005: Found 3 idle states
[    0.456742] ACPI: \_SB_.PLTF.P006: Found 3 idle states
[    0.456916] ACPI: \_SB_.PLTF.P007: Found 3 idle states
[    0.457032] ACPI: \_SB_.PLTF.P008: Found 3 idle states
[    0.457196] ACPI: \_SB_.PLTF.P009: Found 3 idle states
[    0.457346] ACPI: \_SB_.PLTF.P00A: Found 3 idle states
[    0.457480] ACPI: \_SB_.PLTF.P00B: Found 3 idle states
[    0.457626] ACPI: \_SB_.PLTF.P00C: Found 3 idle states
[    0.457761] ACPI: \_SB_.PLTF.P00D: Found 3 idle states
[    0.457875] ACPI: \_SB_.PLTF.P00E: Found 3 idle states
[    0.458013] ACPI: \_SB_.PLTF.P00F: Found 3 idle states
[    0.458965] ACPI: thermal: Thermal Zone [THRM] (65 C)
[    0.575061] ACPI: battery: Slot [BAT1] (battery present)
[    0.748388] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GP17.MP2], AE_NOT_FOUND (20210730/psargs-330)
[    0.751673] ACPI Error: Aborting method \_SB.GPIO._EVT due to previous error (AE_NOT_FOUND) (20210730/psparse-529)
[    0.950961] ACPI: video: Video Device [VGA] (multi-head: yes  rom: no  post: no)
[    1.241411] amdgpu 0000:03:00.0: amdgpu: ACPI VFCT table present but broken (too short #2),skipping
[    5.727785] input: gpio-keys as /devices/platform/ACPI0011:00/gpio-keys.6.auto/input/input15
[  277.927471] ACPI Error: No handler for Region [VRTC] (000000008a515200) [SystemCMOS] (20210730/evregion-130)
[  277.927501] ACPI Error: Region SystemCMOS (ID=5) has no handler (20210730/exfldio-261)
[  277.927551] ACPI Error: Aborting method \_SB.PCI0.SBRG.EC._Q9A due to previous error (AE_NOT_EXIST) (20210730/psparse-529)
```
This is the output of `sudo dmesg | grep ACPI`. And I'm not sure what is the exact problem except the fact that using the os with acpi=off parameter fixes the problem but the negative performace impact of it. Second, I don't have those issues in ubuntu 22.04 and fedora40.

**Comment by glpnk** [comment] 2024-12-09 10:50
`acpi=off` this don't fixes the problem but masks it

What you mean by frozen OS exactly? Does laptop react on caps lock when frozen?

It may be caused by many factors, from things causing kernel panic, to case when laptop going to sleep by auto suspend and can't boot because NVMe SSD have quirks not added to driver (happened to me, but someone fixed it).

So please use latest distro updates

**Comment by glpnk** [comment] 2024-12-09 10:51
> Hello I'm using MSI Delta 15 with ryzen7 5800h and not updated the bios into latest version (which is released in 2023) and I'm currently using the one released in 2022. I'm getting those acpi errors while booting into ubuntu 20.04.6 and freezes my laptop after a while in os. But I don't have problem like tat when I disable acpi by booting with parameter acpi=off. Will the latest driver fix my issue ? Or could anyone manged to fix those ACPI errors ?

I think BIOS update will not make your life worse, so try it

**Comment by mutchiko** [comment] 2024-12-09 22:33
>[    0.267060] ACPI: Added _OSI(Processor Aggregator Device)
[    0.267060] ACPI: Added _OSI(Linux-Dell-Video)
[    0.267060] ACPI: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
[    0.267060] ACPI: Added _OSI(Linux-HPI-Hybrid-Graphics)
[    0.267060] ACPI: Added _OSI(Linux)

acpi problems are so common nowadays that even distros are pre-configured to throw random shit at bios when booting

>the fact that using the os with acpi=off parameter fixes the problem

@MHLeventoglu you have less acpi errors than me, and non of these errors can freeze the system. does the system freeze while doing something in full screen like a game or some wine apps?

**Comment by MHLeventoglu** [comment] 2024-12-11 09:25
It used to happen while downloading some packages via apt-get or compiling packages. But lately It comes to freeze even by doing nothing, like as soon as I boot into Ubuntu and click some stuff. And none of the keys response when the os froze. I've given up on using Ubuntu 20.04 instead I installed Ubuntu 22.04. My main reason on insisting on using Ubuntu 20.04 was to use Ros 1 but I kinda migrated to Ros 2 because my hardware seems to be incompatible to Ubuntu 20.04. Thanks for all of your help.

Additionally updating my BIOS didn't fix anything.

**Comment by glpnk** [comment] 2024-12-11 13:35
Do you have a problem with random freezes on Windows? Try it, because it may be a hardware issue

**Comment by mutchiko** [comment] 2024-12-12 21:08
@MHLeventoglu i remember having a similar issue when i first got my alpha 17 (almost same specs as your laptop) and i was on an arch based distro, i remember playing with the bios settings to get things working, mainly the resize-bar being off stopped some freezing that used to happen; but this issue was long gone for me.

please don't play with bios if you don't know what you're doing because some settings don't go back to default after bios reset and you might end up bricking your laptop.

one thing that is safe to try is to run ```sudo dmesg``` and ```journalctl -f``` from time to time and read the output, it will be long to copy and paste here, so you just have to read it and see what parts of the system that are signaling warnings and errors; or just use Ksystemlogs for a graphical solution that gives you more info and updates automatically.

the dGPU is an AMD RX6000 i assume, they can be problematic, give [this problem](https://bbs.archlinux.org/viewtopic.php?id=285882) on arch forums a look, playing with acpi also means playing with gpu power management related to these kernel boot parameters ```amdgpu.dpm=0 amdgpu.aspm=0 amdgpu.runpm=0 amdgpu.bapm=0 pcie_aspm=off``` so it might be related.

also did you try changing desktop environments? or even try windows to see if the issue is not hardware related? (i doubt).

**Comment by MHLeventoglu** [comment] 2024-12-20 14:25
Firstly sorry I didn't returned in time. I'm currently using windows and Ubuntu 22.04 in dual boot. And everything is OK. No acpi errors or freezes in both windows and 22.04. I guess it was an incompatibility issue. 
But there is one thing which also makes me think it could be a hardware issue. On both Ubuntu 22.04 and 0.04 installations and only a try of installing fedora 40 (only to see whether it gives the same error), installations could not be done properly. Mostly they gave an error like grub-install failed. And I fixed this by installing grub manually by live Linux environment (except the Ubuntu 22.04 was installed successfully after 5 or six tries which is ridiculous). I also fully wiped all of my disks then installed Ubuntu and windows, and windows installed successfully in first attempt.

**Comment by mutchiko** [comment] 2024-12-20 14:36
@MHLeventoglu go ahead and disable fast boot and quiet boot from the bios boot menu (use the keyboard combo to unlock the hidden settings). fast boot can delete uefi boot entries sometimes and doesn't affect boot time in anyway (but it will solve undetected wifi card issues)

most grub errors that i've seen are related to these two bios options, i have them disabled and didn't reinstall linux since 10 months ago.

**Comment by MHLeventoglu** [comment] 2024-12-22 09:07
Ahh, thank you very much. I did not mentione the wifi issue but thanks you mentioned it. I did try disabling fast boot but didn't know about the other option (quiet boot) in bios.

**Comment by mutchiko** [comment] 2024-12-22 18:39
@MHLeventoglu glad i could help, was that the last of your issues?
@Elhossainy-Ahmed are the acpi errors you reported causing you any problems other than the delayed charger detection?

**Comment by MHLeventoglu** [comment] 2024-12-22 19:37
Yesthat was the last issue I had with dual boot. Thaks again!

**Closed** 2024-12-22 20:06 UTC
Labels: bug
